stages:
  - lint
  - test

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/lint.txt
    - flake8 --verbose

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

unit-test:
  stage: test
  services:
    - docker:dind
  script:
    - apt-get update &&
    - apt-get install -y docker.io &&
    - apt-get clean
    - pip install -r requirements/test.txt
    - cd clash_of_code/docker/images/python
    - systemctl start docker
    - docker build -t python3_11_image .
    - cd ..
    - cd ..
    - cd ..
    - python3 manage.py test

