stages:
  - lint
  - test

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/lint.txt
    - flake8 --verbose

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

docker-build:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - cd clash_of_code/docker/images/python
    - docker build -t python3_11_image .

unit-test:
  stage: test
  image: python
  script:
    - pip install -r requirements/test.txt
    - cd clash_of_code
    - python3 manage.py test

